# Copyright (c) 2010-2012, Sowicm
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
# * Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
# * Neither the name of the Sowicm nor the names of its contributors may be
# used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

import os
from os.path import join, dirname, abspath

#Import('env')

slib_root = os.environ['slib_root']
source_files = Glob('index/*.cpp')
# source_files += Split("""
#     cgi/SCGIApp.cpp
#     cgi/SCGIIn.cpp
#     cgi/SCGIOut.cpp
#     cgi/SCookie.cpp
#     cgi/SGet.cpp
#     cgi/SPost.cpp
#     algorithm/md5.cpp
#     core/mail.cpp
#     mysql/SMySQL.cpp
#     """)
Repository(join(slib_root, 'src'))
Program('bin/index', source_files)

#    : requirements
#      <include>$(slib_root)/include
#      <include>$(slib_root)/include/core
#      <include>$(slib_root)/third_party
#      <include>$(slib_root)/include/cgi # obsolete
#      <include>$(slib_root)/include/mysql # obsolete
#      <library-path>$(prj_root)/lib
#      <threading>multi
#      <link>shared
#      <runtime-link>shared
#      <optimization>space
#    ;
#src_list = [ glob-tree *.h *.hpp *.c *.cpp *.cxx : .svn os_*.c ] ;

#src_list += [ glob $(slib_root)/third_party/libfcgi/*.* : .svn os_*.c ] ;
# if NT
# {
#    using msvc ;
#    src_list += $(slib_root)/third_party/libfcgi/os_win32.c ;
# }
# else
# {
#     using gcc ;
#     src_list += $(slib_root)/third_party/libfcgi/os_unix.c ;
# }

#exe index : $(src_list) :
#    <variant>debug:<define>_DEBUG
#    <toolset>msvc:<cflags>/GA
#    ;
#if NT
#{
#    install dist : index : <location>../htdocs/bin ;
#}
#else
#{
#    install dist : index : <location>../dist/bin/unix ;
#}
